Build: Fixed dependency script not updating boost library
The dependency script now downloads recursively every submodules except for QT

diff --git a/.github/workflows/cmake-single-platform.yml b/.github/workflows/cmake-single-platform.yml
--- a/.github/workflows/cmake-single-platform.yml
+++ b/.github/workflows/cmake-single-platform.yml
@@ -16,18 +16,8 @@ jobs:
   build:
     runs-on: ubuntu-latest
 
-    steps:
+    steps':
     - uses: actions/checkout@v4
-
-    - name: Install Qt
-      uses: jurplel/install-qt-action@v4
-      with :
-        version: "6.3.*"
-        host: 'linux'
-        target: 'desktop'
-        arch: 'gcc_64'
-        install-deps: 'true'
-
 
     - name: Install Axomae dependencies
       run: |
@@ -38,7 +28,7 @@ jobs:
         sudo apt-get install -y libgl1-mesa-dev libglew-dev
 
     - name: Configure CMake
-      run: cmake -B ${{github.workspace}}/../build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DAXOMAE_BUILD_TESTS:BOOL=${{env.BUILD_TESTS}} -DAXOMAE_LUT_MEDIUMP:BOOL=ON -DAXOMAE_FROMSOURCE_QT_BUILD=OFF
+      run: cmake -B ${{github.workspace}}/../build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DAXOMAE_BUILD_TESTS:BOOL=${{env.BUILD_TESTS}} -DAXOMAE_LUT_MEDIUMP:BOOL=ON -DAXOMAE_FROMSOURCE_QT_BUILD=ON
 
     - name: Build
       run: cmake --build ${{github.workspace}}/../build --config ${{env.BUILD_TYPE}}
@@ -50,6 +40,6 @@ jobs:
 
     #####################################################
     # For debugging , opens an ssh cli
-    - name: Setup tmate session
-      if: success() || failure()
-      uses: mxschmitt/action-tmate@v3
+   # - name: Setup tmate session
+    #  if: success() || failure()
+    #  uses: mxschmitt/action-tmate@v3
